/* Caspian Bridge — catalogue data. Prices are indicative export levels (USD), mid-2026.
   Sources: supplier price lists, APK-Inform, Tridge, LME references; "est" where no public quote existed. */
window.CB_DATA = {
  asOf: '2026-09-13',
  fx: { usdKzt: 455, usdIrrOfficial: 1375000, usdIrrMarket: 2340000 },
  freight: {
    sea:   { perTonne: 35,  per40ft: 2200, minCharge: 350, days: [10, 14] },
    rail:  { perTonne: 75,  per40ft: 3200, minCharge: 500, days: [12, 18] },
    truck: { perTonne: 300, per40ft: 5000, minCharge: 900, days: [7, 10] }
  },
  cats: {
    fruits:   { ru: 'Фрукты',            en: 'Fruit' },
    nuts:     { ru: 'Орехи',             en: 'Nuts' },
    dried:    { ru: 'Сухофрукты',        en: 'Dried fruit' },
    spices:   { ru: 'Специи',            en: 'Spices' },
    tea:      { ru: 'Чай и травы',       en: 'Tea & herbs' },
    carpets:  { ru: 'Ковры',             en: 'Carpets' },
    building: { ru: 'Стройматериалы',    en: 'Building materials' },
    petro:    { ru: 'Нефтехимия',        en: 'Petrochemicals' },
    chem:     { ru: 'Химия',             en: 'Chemicals' },
    medical:  { ru: 'Медицина',          en: 'Medical' },
    textile:  { ru: 'Текстиль',          en: 'Textile' },
    grain:    { ru: 'Зерно и мука',      en: 'Grain & flour' },
    oils:     { ru: 'Масла и масличные', en: 'Oils & oilseeds' },
    meat:     { ru: 'Мясо',              en: 'Meat' },
    metals:   { ru: 'Металлы',           en: 'Metals' },
    energy:   { ru: 'Энергоресурсы',     en: 'Energy' },
    machines: { ru: 'Машины',            en: 'Machinery' },
    fert:     { ru: 'Удобрения',         en: 'Fertilizers' }
  },
  units: {
    t:    { ru: 'т',    en: 't',    tonnes: 1 },
    kg:   { ru: 'кг',   en: 'kg',   tonnes: 0.001 },
    m2:   { ru: 'м²',   en: 'm²' },
    m:    { ru: 'м',    en: 'm' },
    pc:   { ru: 'шт',   en: 'pc' },
    pair: { ru: 'пара', en: 'pair' }
  },
  products: [
    /* ───────────── IRAN → KAZAKHSTAN ───────────── */
    { id: 'dates', dir: 'ir', cat: 'fruits', top: true, price: 1750, unit: 't', hs: '080410', inc: 'FOB Bandar Abbas', lead: 12, suppliers: 9,
      name: { ru: 'Финики Мазафати', en: 'Mazafati dates', fa: 'خرمای مضافتی' },
      spec: { ru: 'Сорт A, влажность 22–24 %, картон 5–10 кг. Сайер — от 1 150 $/т', en: 'Grade A, moisture 22–24 %, 5–10 kg cartons. Sayer from $1,150/t' },
      moq: { ru: '1 × 20ft (≈24 т)', en: '1 × 20ft (≈24 t)' }, origin: { ru: 'Бам, Керман', en: 'Bam, Kerman' } },
    { id: 'kiwi', dir: 'ir', cat: 'fruits', price: 900, unit: 't', hs: '081050', inc: 'FOB Bandar Abbas', lead: 8, suppliers: 5,
      name: { ru: 'Киви свежий', en: 'Fresh kiwifruit', fa: 'کیوی تازه' },
      spec: { ru: 'Хайвард, калибр 28–36, рефконтейнер. Уточнять экспортные ограничения на сезон', en: 'Hayward, count 28–36, reefer. Check seasonal export restrictions' },
      moq: { ru: '1 рефконтейнер (≈20 т)', en: '1 reefer (≈20 t)' }, origin: { ru: 'Мазандаран', en: 'Mazandaran' } },
    { id: 'pomegranate', dir: 'ir', cat: 'fruits', price: 1100, unit: 't', hs: '081090', inc: 'FOB Bandar Abbas', lead: 8, suppliers: 7,
      name: { ru: 'Гранат свежий', en: 'Fresh pomegranate', fa: 'انار تازه' },
      spec: { ru: 'Малас / Раббаб, калибр 8–10 см, холодовая цепь', en: 'Malas / Rabbab, 8–10 cm, cold chain' },
      moq: { ru: '1 рефконтейнер', en: '1 reefer' }, origin: { ru: 'Саве, Маркази', en: 'Saveh, Markazi' } },
    { id: 'oranges', dir: 'ir', cat: 'fruits', price: 600, unit: 't', hs: '080510', inc: 'FOB Bandar Abbas', lead: 8, suppliers: 6,
      name: { ru: 'Апельсины', en: 'Oranges', fa: 'پرتقال' },
      spec: { ru: 'Томсон / Валенсия, калибр 56–72, вощёные', en: 'Thomson / Valencia, size 56–72, waxed' },
      moq: { ru: '1 × 40ft реф', en: '1 × 40ft reefer' }, origin: { ru: 'Мазандаран', en: 'Mazandaran' } },
    { id: 'lemons', dir: 'ir', cat: 'fruits', price: 750, unit: 't', hs: '080550', inc: 'FOB Bandar Abbas', lead: 8, suppliers: 4,
      name: { ru: 'Лимоны', en: 'Lemons', fa: 'لیمو ترش' },
      spec: { ru: 'Тип Лиссабон, калибр 54–75 мм', en: 'Lisbon type, 54–75 mm' },
      moq: { ru: '1 × 40ft реф', en: '1 × 40ft reefer' }, origin: { ru: 'Джахром, Фарс', en: 'Jahrom, Fars' } },
    { id: 'grapes', dir: 'ir', cat: 'fruits', price: 1300, unit: 't', hs: '080610', inc: 'FOB Bandar Abbas', lead: 8, suppliers: 5,
      name: { ru: 'Виноград столовый', en: 'Table grapes', fa: 'انگور' },
      spec: { ru: 'Аскари / кишмиш, вентилируемые ящики, холодовая цепь', en: 'Askari / seedless, ventilated boxes, cold chain' },
      moq: { ru: '1 рефконтейнер', en: '1 reefer' }, origin: { ru: 'Малайер, Хамадан', en: 'Malayer, Hamadan' } },
    { id: 'pistachios', dir: 'ir', cat: 'nuts', top: true, price: 7500, unit: 't', hs: '080251', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 12,
      name: { ru: 'Фисташки в скорлупе', en: 'In-shell pistachios', fa: 'پسته' },
      spec: { ru: 'Акбари ≈7 750 $/т, Фандоги 24/26 ≈7 350 $/т. Ядро — в 2–3 раза дороже', en: 'Akbari ≈$7,750/t, Fandoghi 24/26 ≈$7,350/t. Kernels 2–3× higher' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Рафсанджан, Керман', en: 'Rafsanjan, Kerman' } },
    { id: 'almonds', dir: 'ir', cat: 'nuts', price: 7500, unit: 't', hs: '080212', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 6,
      name: { ru: 'Миндаль, ядро', en: 'Almond kernels', fa: 'مغز بادام' },
      spec: { ru: 'Мамаи / Раби, натуральное ядро, 23–25 шт/унция', en: 'Mamaei / Rabie, natural kernel, 23–25/oz' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Саман, Чахармахал', en: 'Saman, Chaharmahal' } },
    { id: 'raisins', dir: 'ir', cat: 'dried', price: 2900, unit: 't', hs: '080620', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 8,
      name: { ru: 'Изюм голден / султана', en: 'Golden / sultana raisins', fa: 'کشمش' },
      spec: { ru: 'Солнечная сушка, 4-кратная очистка, влажность < 18 %', en: 'Sun-dried, 4-way cleaned, moisture < 18 %' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Малайер, Хамадан', en: 'Malayer, Hamadan' } },
    { id: 'dried-apricots', dir: 'ir', cat: 'dried', price: 4500, unit: 't', hs: '081310', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 5,
      name: { ru: 'Курага', en: 'Dried apricots', fa: 'قیسی' },
      spec: { ru: 'Калибр 30–40 мм, с обработкой SO₂ или без', en: '30–40 mm, SO₂-treated or natural' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Маранд, Вост. Азербайджан', en: 'Marand, East Azerbaijan' } },
    { id: 'figs', dir: 'ir', cat: 'dried', price: 7000, unit: 't', hs: '080420', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 4,
      name: { ru: 'Инжир сушёный', en: 'Dried figs', fa: 'انجیر خشک' },
      spec: { ru: 'Эстахбан, естественная сушка, светлый, сорт A', en: 'Estahban, sun-dried, light colour, grade A' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Эстахбан, Фарс', en: 'Estahban, Fars' } },
    { id: 'saffron', dir: 'ir', cat: 'spices', top: true, price: 1500, unit: 'kg', hs: '091020', inc: 'FOB Mashhad (авиа)', lead: 5, suppliers: 11,
      name: { ru: 'Шафран Негин / Саргол', en: 'Saffron Negin / Sargol', fa: 'زعفران نگین' },
      spec: { ru: 'ISO 3632 категория 1. Негин 1 500–1 580 $/кг, Саргол 1 400–1 480 $/кг', en: 'ISO 3632 cat. 1. Negin $1,500–1,580/kg, Sargol $1,400–1,480/kg' },
      moq: { ru: '1–5 кг (розн.-экспорт), 25 кг опт', en: '1–5 kg (retail-export), 25 kg bulk' }, origin: { ru: 'Торбете-Хейдерие, Хорасан', en: 'Torbat-e Heydarieh, Khorasan' } },
    { id: 'turmeric', dir: 'ir', cat: 'spices', price: 2200, unit: 't', hs: '091030', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 3,
      name: { ru: 'Куркума', en: 'Turmeric', fa: 'زردچوبه' },
      spec: { ru: 'Молотая / корень, куркумин 3–5 %. Преимущественно реэкспорт', en: 'Ground / finger, curcumin 3–5 %. Mostly re-export grade' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Тегеран (переработка)', en: 'Tehran (processing)' } },
    { id: 'cumin', dir: 'ir', cat: 'spices', price: 3200, unit: 't', hs: '090931', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 4,
      name: { ru: 'Зира (кумин)', en: 'Cumin seed', fa: 'زیره سبز' },
      spec: { ru: 'Целое семя, чистота 99 %, влажность < 9 %', en: 'Whole seed, purity 99 %, moisture < 9 %' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Хорасан', en: 'Khorasan' } },
    { id: 'sumac', dir: 'ir', cat: 'spices', price: 2500, unit: 't', hs: '091099', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 3,
      name: { ru: 'Сумах молотый', en: 'Ground sumac', fa: 'سماق' },
      spec: { ru: 'Тёмно-красный, пищевой, без соли', en: 'Deep red, food grade, no salt' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Курдистан', en: 'Kurdistan' } },
    { id: 'tea', dir: 'ir', cat: 'tea', price: 2000, unit: 't', hs: '090240', inc: 'FOB Bandar Abbas / CPT Almaty', lead: 14, suppliers: 6,
      name: { ru: 'Чай чёрный лахиджанский', en: 'Lahijan black tea', fa: 'چای سیاه لاهیجان' },
      spec: { ru: 'Ортодокс / CTC. Сырец от 1 200 $/т, фасованный до 3 000 $/т', en: 'Orthodox / CTC. Bulk from $1,200/t, packaged up to $3,000/t' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Лахиджан, Гилян', en: 'Lahijan, Gilan' } },
    { id: 'carpets', dir: 'ir', cat: 'carpets', price: 250, unit: 'm2', hs: '570110', inc: 'CPT Almaty', lead: 10, suppliers: 14,
      name: { ru: 'Ковры ручной работы', en: 'Hand-knotted carpets', fa: 'فرش دستباف' },
      spec: { ru: 'Шерсть, 150–300 тыс. узлов/м², городские дизайны. Сертификат подлинности', en: 'Wool, 150–300k knots/m², city designs. Certificate of authenticity' },
      moq: { ru: 'от 1 шт (партии 20–50 м²)', en: 'from 1 piece (lots 20–50 m²)' }, origin: { ru: 'Тебриз, Кашан, Исфахан', en: 'Tabriz, Kashan, Isfahan' } },
    { id: 'ceramic-tile', dir: 'ir', cat: 'building', top: true, price: 5.8, unit: 'm2', hs: '690722', inc: 'FOB Bandar Abbas', lead: 21, suppliers: 16,
      name: { ru: 'Плитка керамическая', en: 'Ceramic tile', fa: 'کاشی و سرامیک' },
      spec: { ru: 'Глазурованная 60 × 60 см, PEI III, 1-й сорт. Керамогранит от 7 $/м²', en: 'Glazed 60 × 60 cm, PEI III, 1st grade. Porcelain from $7/m²' },
      moq: { ru: '1 × 20ft (≈1 000 м²)', en: '1 × 20ft (≈1,000 m²)' }, origin: { ru: 'Йезд, Мейбод', en: 'Yazd, Meybod' } },
    { id: 'cement', dir: 'ir', cat: 'building', price: 50, unit: 't', hs: '252329', inc: 'FOB Bandar Abbas', lead: 21, suppliers: 8,
      name: { ru: 'Цемент портланд', en: 'Portland cement', fa: 'سیمان پرتلند' },
      spec: { ru: 'CEM I 42.5R, мешки 50 кг / биг-бэг. Клинкер 28–32 $/т', en: 'CEM I 42.5R, 50 kg bags / jumbo. Clinker $28–32/t' },
      moq: { ru: 'от 500 т', en: 'from 500 t' }, origin: { ru: 'Хормозган', en: 'Hormozgan' } },
    { id: 'stone', dir: 'ir', cat: 'building', price: 22, unit: 'm2', hs: '680229', inc: 'FOB Bandar Abbas', lead: 21, suppliers: 10,
      name: { ru: 'Травертин, мрамор', en: 'Travertine & marble', fa: 'سنگ تراورتن' },
      spec: { ru: 'Травертин 30 × 60 × 2 см, шлифованный. Мрамор премиум 60–100 $/м²', en: 'Travertine 30 × 60 × 2 cm, honed. Premium marble $60–100/m²' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Махаллат, Маркази', en: 'Mahallat, Markazi' } },
    { id: 'glass', dir: 'ir', cat: 'building', price: 5, unit: 'm2', hs: '700529', inc: 'FOB Bandar Abbas', lead: 21, suppliers: 4,
      name: { ru: 'Стекло флоат', en: 'Float glass', fa: 'شیشه فلوت' },
      spec: { ru: 'Прозрачное 4–6 мм, в тоннах ≈450–500 $/т', en: 'Clear 4–6 mm, ≈$450–500/t on tonne basis' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Кавех, Саве', en: 'Kaveh, Saveh' } },
    { id: 'bitumen', dir: 'ir', cat: 'petro', top: true, price: 415, unit: 't', hs: '271320', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 9,
      name: { ru: 'Битум 60/70', en: 'Bitumen 60/70', fa: 'قیر ۶۰/۷۰' },
      spec: { ru: 'Пенетрация 60/70, биг-бэги. Налив ≈335 $/т, стальные бочки ≈425 $/т', en: 'Pen grade 60/70, jumbo bags. Bulk ≈$335/t, new steel drums ≈$425/t' },
      moq: { ru: '20–24 т (автопартия) / судно', en: '20–24 t truckload / vessel' }, origin: { ru: 'Исфахан, Бендер-Аббас', en: 'Isfahan, Bandar Abbas' } },
    { id: 'polymers', dir: 'ir', cat: 'petro', price: 850, unit: 't', hs: '390120', inc: 'FOB Bandar Imam', lead: 14, suppliers: 7,
      name: { ru: 'Полимеры ПНД / ПП', en: 'HDPE / PP granules', fa: 'پلی‌اتیلن و پلی‌پروپیلن' },
      spec: { ru: 'ПНД литьевой / выдувной, первичный. ПП гомополимер ≈900 $/т', en: 'HDPE injection / blow, virgin. PP homopolymer ≈$900/t' },
      moq: { ru: '1 × 20ft (20–24 т)', en: '1 × 20ft (20–24 t)' }, origin: { ru: 'Махшахр, Хузестан', en: 'Mahshahr, Khuzestan' } },
    { id: 'plastics', dir: 'ir', cat: 'petro', price: 800, unit: 't', hs: '390410', inc: 'FOB Bandar Imam', lead: 14, suppliers: 5,
      name: { ru: 'ПВХ суспензионный', en: 'PVC suspension resin', fa: 'پی‌وی‌سی' },
      spec: { ru: 'S65 / S70, K-value 65–70', en: 'S65 / S70, K-value 65–70' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Бендер-Имам, Хузестан', en: 'Bandar Imam, Khuzestan' } },
    { id: 'household-chem', dir: 'ir', cat: 'chem', price: 800, unit: 't', hs: '340220', inc: 'FOB Bandar Abbas', lead: 14, suppliers: 6,
      name: { ru: 'Бытовая химия', en: 'Household chemicals', fa: 'مواد شوینده' },
      spec: { ru: 'Стиральный порошок, мешки 20–25 кг. Жидкие средства — по запросу', en: 'Laundry powder, 20–25 kg bags. Liquids on request' },
      moq: { ru: '1 × 20ft', en: '1 × 20ft' }, origin: { ru: 'Казвин', en: 'Qazvin' } },
    { id: 'medical', dir: 'ir', cat: 'medical', price: null, unit: 'pc', hs: '300490', inc: 'CPT Almaty (авиа)', lead: 30, suppliers: 3,
      name: { ru: 'Лекарства и расходники', en: 'Medicines & consumables', fa: 'دارو و لوازم پزشکی' },
      spec: { ru: 'Дженерики 0,01–0,05 $/ед., шприцы, перчатки 0,03–0,10 $/ед. Требуется регистрация в МЗ РК', en: 'Generics $0.01–0.05/unit, syringes & gloves $0.03–0.10/unit. KZ MoH registration required' },
      moq: { ru: 'от 10 000 ед. на SKU', en: 'from 10,000 units per SKU' }, origin: { ru: 'Тегеран', en: 'Tehran' } },
    { id: 'fabrics', dir: 'ir', cat: 'textile', price: 3.5, unit: 'm', hs: '520852', inc: 'FOB Bandar Abbas', lead: 21, suppliers: 9,
      name: { ru: 'Ткани', en: 'Fabrics', fa: 'پارچه' },
      spec: { ru: 'Хлопок / полиэстер, 150–180 г/м², ширина 150 см', en: 'Cotton / poly blend, 150–180 g/m², 150 cm width' },
      moq: { ru: '3 000–5 000 м', en: '3,000–5,000 m' }, origin: { ru: 'Йезд, Кашан', en: 'Yazd, Kashan' } },
    { id: 'clothing', dir: 'ir', cat: 'textile', price: 6, unit: 'pc', hs: '610910', inc: 'FOB Bandar Abbas', lead: 30, suppliers: 12,
      name: { ru: 'Одежда', en: 'Clothing', fa: 'پوشاک' },
      spec: { ru: 'Базовый трикотаж, размерная сетка, private label', en: 'Basic knitwear, size runs, private label' },
      moq: { ru: '1 000–3 000 шт / модель', en: '1,000–3,000 pcs / style' }, origin: { ru: 'Тегеран', en: 'Tehran' } },
    { id: 'footwear', dir: 'ir', cat: 'textile', price: 9, unit: 'pair', hs: '640399', inc: 'FOB Bandar Abbas', lead: 30, suppliers: 8,
      name: { ru: 'Обувь', en: 'Footwear', fa: 'کفش' },
      spec: { ru: 'Повседневная, верх кожа / синтетика', en: 'Casual, leather / synthetic upper' },
      moq: { ru: '1 000–2 000 пар / модель', en: '1,000–2,000 pairs / model' }, origin: { ru: 'Тебриз', en: 'Tabriz' } },

    /* ───────────── KAZAKHSTAN → IRAN ───────────── */
    { id: 'wheat', dir: 'kz', cat: 'grain', top: true, price: 245, unit: 't', hs: '100199', inc: 'FOB Aktau', lead: 10, suppliers: 18,
      name: { ru: 'Пшеница 3 класс', en: 'Milling wheat, 3rd class', fa: 'گندم' },
      spec: { ru: 'Клейковина 23–25 %, протеин ≈12,5 %, ГОСТ', en: 'Gluten 23–25 %, protein ≈12.5 %, GOST' },
      moq: { ru: 'вагон 68 т / судовая партия', en: 'rail wagon 68 t / vessel lot' }, origin: { ru: 'Костанай, СКО', en: 'Kostanay, North KZ' } },
    { id: 'barley', dir: 'kz', cat: 'grain', price: 235, unit: 't', hs: '100300', inc: 'FOB Aktau', lead: 10, suppliers: 11,
      name: { ru: 'Ячмень фуражный', en: 'Feed barley', fa: 'جو' },
      spec: { ru: 'Натура 60+ кг/гл, влажность ≤ 14 %', en: 'Test weight 60+ kg/hl, moisture ≤ 14 %' },
      moq: { ru: 'вагон / судовая партия', en: 'rail wagon / vessel lot' }, origin: { ru: 'Акмолинская обл.', en: 'Akmola region' } },
    { id: 'flour', dir: 'kz', cat: 'grain', top: true, price: 330, unit: 't', hs: '110100', inc: 'FOB Aktau / DAP Сарахс', lead: 10, suppliers: 15,
      name: { ru: 'Мука пшеничная в/с, 1 с', en: 'Wheat flour, premium & 1st', fa: 'آرد گندم' },
      spec: { ru: 'Зольность < 0,75 %, мешки 50 кг', en: 'Ash < 0.75 %, 50 kg bags' },
      moq: { ru: 'вагон (≈60 т)', en: 'rail wagon (≈60 t)' }, origin: { ru: 'Костанай', en: 'Kostanay' } },
    { id: 'sunflower-oil', dir: 'kz', cat: 'oils', top: true, price: 1050, unit: 't', hs: '151219', inc: 'FOB Aktau', lead: 12, suppliers: 7,
      name: { ru: 'Масло подсолнечное', en: 'Sunflower oil', fa: 'روغن آفتابگردان' },
      spec: { ru: 'Рафинированное дезодорированное. Сырое (FFA < 2 %) ≈900 $/т', en: 'RBD. Crude (FFA < 2 %) ≈$900/t' },
      moq: { ru: 'флекситанк 20–24 т', en: 'flexitank 20–24 t' }, origin: { ru: 'ВКО, Павлодар', en: 'East KZ, Pavlodar' } },
    { id: 'flax', dir: 'kz', cat: 'oils', price: 700, unit: 't', hs: '120400', inc: 'FOB Aktau', lead: 12, suppliers: 6,
      name: { ru: 'Лён масличный', en: 'Flax seed', fa: 'تخم کتان' },
      spec: { ru: 'Масличность 40 %+, чистота 99 %', en: 'Oil content 40 %+, purity 99 %' },
      moq: { ru: 'вагон', en: 'rail wagon' }, origin: { ru: 'СКО, Костанай', en: 'North KZ, Kostanay' } },
    { id: 'rapeseed', dir: 'kz', cat: 'oils', price: 510, unit: 't', hs: '120510', inc: 'FOB Aktau', lead: 12, suppliers: 5,
      name: { ru: 'Рапс', en: 'Rapeseed', fa: 'کلزا' },
      spec: { ru: 'Масличность 42 %+, канольный тип', en: 'Oil content 42 %+, canola type' },
      moq: { ru: 'вагон', en: 'rail wagon' }, origin: { ru: 'СКО', en: 'North KZ' } },
    { id: 'beef', dir: 'kz', cat: 'meat', price: 6.2, unit: 'kg', hs: '020230', inc: 'FOB Aktau / CPT Almaty', lead: 14, suppliers: 9,
      name: { ru: 'Говядина халяль', en: 'Halal beef', fa: 'گوشت گاو حلال' },
      spec: { ru: 'Замороженная бескостная, сертификат халяль, ветсертификат', en: 'Frozen boneless, halal & veterinary certificates' },
      moq: { ru: '1 × 40ft реф (20–24 т)', en: '1 × 40ft reefer (20–24 t)' }, origin: { ru: 'Костанай, ВКО', en: 'Kostanay, East KZ' } },
    { id: 'lamb', dir: 'kz', cat: 'meat', price: 5.0, unit: 'kg', hs: '020430', inc: 'FOB Aktau / CPT Almaty', lead: 14, suppliers: 8,
      name: { ru: 'Баранина халяль', en: 'Halal lamb & mutton', fa: 'گوشت گوسفند حلال' },
      spec: { ru: 'Замороженная, на кости / бескостная', en: 'Frozen, bone-in / boneless' },
      moq: { ru: '1 × 40ft реф', en: '1 × 40ft reefer' }, origin: { ru: 'Туркестан, Жамбыл', en: 'Turkestan, Zhambyl' } },
    { id: 'copper', dir: 'kz', cat: 'metals', top: true, price: 10200, unit: 't', hs: '740311', inc: 'FOB Aktau', lead: 21, suppliers: 3,
      name: { ru: 'Медь катодная', en: 'Copper cathode', fa: 'کاتد مس' },
      spec: { ru: 'Grade A, 99,99 % Cu, привязка к LME', en: 'Grade A, 99.99 % Cu, LME-linked' },
      moq: { ru: 'контейнер 20–25 т', en: 'container 20–25 t' }, origin: { ru: 'Жезказган, Балхаш', en: 'Zhezkazgan, Balkhash' } },
    { id: 'zinc', dir: 'kz', cat: 'metals', price: 2850, unit: 't', hs: '790111', inc: 'FOB Aktau', lead: 21, suppliers: 2,
      name: { ru: 'Цинк в чушках', en: 'Zinc ingot', fa: 'شمش روی' },
      spec: { ru: 'SHG 99,995 % Zn, привязка к LME', en: 'SHG 99.995 % Zn, LME-linked' },
      moq: { ru: 'контейнер', en: 'container' }, origin: { ru: 'Усть-Каменогорск', en: 'Ust-Kamenogorsk' } },
    { id: 'aluminium', dir: 'kz', cat: 'metals', price: 2650, unit: 't', hs: '760110', inc: 'FOB Aktau', lead: 21, suppliers: 2,
      name: { ru: 'Алюминий первичный', en: 'Primary aluminium', fa: 'شمش آلومینیوم' },
      spec: { ru: 'Чушка P1020, 99,7 % Al, привязка к LME', en: 'P1020 ingot, 99.7 % Al, LME-linked' },
      moq: { ru: 'контейнер', en: 'container' }, origin: { ru: 'Павлодар', en: 'Pavlodar' } },
    { id: 'ferroalloys', dir: 'kz', cat: 'metals', top: true, price: 2000, unit: 't', hs: '720241', inc: 'FOB Aktau', lead: 21, suppliers: 4,
      name: { ru: 'Феррохром HC', en: 'High-carbon ferrochrome', fa: 'فروکروم' },
      spec: { ru: '60–65 % Cr, фракция 10–50 мм', en: '60–65 % Cr, lump 10–50 mm' },
      moq: { ru: 'вагон 60 т', en: 'rail wagon 60 t' }, origin: { ru: 'Актобе, Аксу', en: 'Aktobe, Aksu' } },
    { id: 'coal', dir: 'kz', cat: 'energy', price: 60, unit: 't', hs: '270112', inc: 'FOB Aktau / DAP граница', lead: 14, suppliers: 6,
      name: { ru: 'Уголь энергетический', en: 'Thermal coal', fa: 'زغال سنگ حرارتی' },
      spec: { ru: '4 500–5 500 ккал/кг, зола ≤ 25 %', en: '4,500–5,500 kcal/kg, ash ≤ 25 %' },
      moq: { ru: 'вагон / судовая партия', en: 'rail wagon / vessel lot' }, origin: { ru: 'Экибастуз, Караганда', en: 'Ekibastuz, Karaganda' } },
    { id: 'oil', dir: 'kz', cat: 'energy', price: 315, unit: 't', hs: '271019', inc: 'FOB Aktau', lead: 21, suppliers: 3,
      name: { ru: 'Дизель EN590 и нефть', en: 'Diesel EN590 & crude', fa: 'گازوئیل و نفت خام' },
      spec: { ru: 'Дизель 10 ppm S. Нефть ≈525 $/т (≈72 $/барр.). Межправительственные квоты', en: 'Diesel 10 ppm S. Crude ≈$525/t (≈$72/bbl). Subject to intergovernmental quotas' },
      moq: { ru: 'автопартии / от 50 000 т по контракту', en: 'truck lots / from 50,000 t term' }, origin: { ru: 'Атырау, Мангистау', en: 'Atyrau, Mangystau' } },
    { id: 'chemicals', dir: 'kz', cat: 'chem', price: 100, unit: 't', hs: '250300', inc: 'FOB Aktau', lead: 14, suppliers: 4,
      name: { ru: 'Сера гранулированная', en: 'Granulated sulphur', fa: 'گوگرد گرانوله' },
      spec: { ru: '99,9 %, гранула. Каустик 50 % ≈420 $/т (ISO-танк)', en: '99.9 %, granular. Caustic soda 50 % ≈$420/t (ISO tank)' },
      moq: { ru: 'вагон / судовая партия', en: 'rail wagon / vessel lot' }, origin: { ru: 'Тенгиз, Атырау', en: 'Tengiz, Atyrau' } },
    { id: 'machinery', dir: 'kz', cat: 'machines', price: null, unit: 'pc', hs: '8432–8474', inc: 'CPT Almaty / DAP граница', lead: 45, suppliers: 5,
      name: { ru: 'Машины и оборудование', en: 'Machinery & equipment', fa: 'ماشین‌آلات و تجهیزات' },
      spec: { ru: 'Сельхоз- и горная техника, насосы, запчасти. 2 000–50 000 $/ед. по спецификации', en: 'Agri & mining machinery, pumps, spares. $2,000–50,000/unit by spec' },
      moq: { ru: 'по спецификации', en: 'by specification' }, origin: { ru: 'Астана, Костанай', en: 'Astana, Kostanay' } },
    { id: 'fertilizer', dir: 'kz', cat: 'fert', price: 310, unit: 't', hs: '310230', inc: 'FOB Aktau', lead: 14, suppliers: 4,
      name: { ru: 'Селитра аммиачная, NPK', en: 'Ammonium nitrate & NPK', fa: 'کود شیمیایی' },
      spec: { ru: 'АС 34,4 % N, гранула. NPK 15-15-15 ≈420 $/т', en: 'AN 34.4 % N, granular. NPK 15-15-15 ≈$420/t' },
      moq: { ru: 'вагон 60 т', en: 'rail wagon 60 t' }, origin: { ru: 'Актау, Жамбыл', en: 'Aktau, Zhambyl' } }
  ]
};
